[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
balance-management = { path = "../domain/balance-management" }
wallet-integration = { path = "../domain/wallet-integration" }

anyhow.workspace = true
async-trait.workspace = true
base64 = "0.22.1"
bcs = "0.1.4"
chrono.workspace = true
cqrs-es.workspace = true
iota-gas-station.workspace = true
iota-sdk = { git = "https://github.com/iotaledger/iota", tag = "v1.7.0", package = "iota-sdk" }
iota-types = { git = "https://github.com/iotaledger/iota", tag = "v1.7.0", package = "iota-types" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
