[package]
name = "axum-graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { path = "../../application" }
balance-management = { path = "../../domain/balance-management" }
composition-root = { path = "../../infrastructure/composition-root" }

anyhow.workspace = true
async-graphql = "7.0"
async-graphql-axum = "7.0"
async-trait.workspace = true
axum = { version = "0.8", features = ["ws"] }
bytes = "1.10"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
rand = "0.9"
serde_json = "1.0"
slab = "0.4"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tower-service = "0.3"

cqrs-es.workspace = true
mongo-es = "0.3"
