[package]
name = "axum-graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { path = "../../application" }
balance-management = { path = "../../domain/balance-management" }
composition-root = { path = "../../infrastructure/composition-root" }
wallet-integration = { path = "../../domain/wallet-integration" }

anyhow = "1.0"
async-graphql = { version = "7.0", features = ["chrono", "url", "uuid"] }
async-graphql-axum = "7.0"
async-trait.workspace = true
axum = { version = "0.8", features = ["ws"] }
bytes = "1.11"
chrono.workspace = true
futures-util = "0.3"
iota-gas-station.workspace = true
iota-json-rpc-types = { git = "https://github.com/iotaledger/iota", tag = "v1.7.0", package = "iota-json-rpc-types" }
rand.workspace = true
regex = { version = "1" }
serde_json = "1.0"
slab = "0.4"
serde.workspace = true
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tower-service = "0.3"
tower-http = { version = "0.5", features = ["cors"] }
tracing.workspace = true
url.workspace = true
uuid.workspace = true

cqrs-es.workspace = true
mongo-es = "0.3"
