[sources.gas_station_logs]
type = "docker_logs"
include_containers = ["iota-gas-station"]

[sinks.sponsoring_service_webhook]
type = "http"
inputs = ["gas_station_logs"]
# uri = "http://host.docker.internal:8000/webhook/transaction"
uri = "http://iota-sponsoring-service:8000/webhook/transaction"
method = "post"
encoding.codec = "json"
